baseURL = "https://hfc.uw.rso/"
locale = 'en-us'
title = "Husky Flying Club"

[params]
  description = "UW's premier aviation club"
  discord = "https://discord.gg/HnhHpHraU"
  youtube = "https://www.youtube.com/@huskyflyingclub6449"